name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    services:
      # Configuration du service Docker pour les tests
      cypress:
        image: cypress/included:13.16.1
        options: >-
          --entrypoint= 
          --shm-size=2g
        volumes:
          - .:/e2e

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run Cypress Tests
      run: >
        docker run --rm
        -v ${{ github.workspace }}:/e2e
        -w /e2e
        cypress/included:13.16.1
