name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Cypress in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/e2e \
          -w /e2e \
          --shm-size=2g \
          cypress/included:13.16.1 npx cypress run
